#include QMK_KEYBOARD_H

/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
	[0] = LAYOUT(KC_Q, KC_W, KC_F, KC_P, KC_G,                  KC_J, KC_L, KC_U, KC_Y, KC_SCLN,
                KC_A, KC_R, KC_S, KC_T, KC_D,                  KC_H, KC_N, KC_E, KC_I, KC_O,
                KC_Z, KC_X, KC_C, KC_V, KC_B, KC_GRV, KC_BSLS, KC_K, KC_M, KC_COMM, KC_DOT, KC_SLSH,
                KC_TAB, KC_LGUI, TT(3), KC_LSFT, KC_BSPC, KC_LCTL, KC_LALT, KC_SPC, TT(1), KC_MINS, KC_QUOT, KC_ENT),
	[1] = LAYOUT(KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0,
                KC_LPRN, KC_RPRN, KC_NO, KC_LCBR, KC_RCBR, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_PLUS,
                KC_LBRC, KC_RBRC, KC_NO, KC_LT, KC_GT, KC_EQL, KC_NO, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_MINS,
                KC_NO, LALT(KC_SPC), TT(0), KC_LSFT, KC_DEL, KC_LCTL, KC_LALT, KC_SPC, TT(2), KC_DOT, KC_EQL, KC_ESC),
    [2] = LAYOUT(KC_Q, KC_W, KC_E,  KC_R, KC_T,                  KC_Y, KC_U, KC_I, KC_O, KC_P,
                KC_A, KC_S, KC_D, KC_F, KC_G,                  KC_H, KC_J, KC_K, KC_L, KC_SCLN,
                KC_Z, KC_X, KC_C, KC_V, KC_B, KC_GRV, KC_BSLS, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH,
                KC_TAB, KC_LGUI, TT(1), KC_LSFT, KC_BSPC, KC_LCTL, KC_LALT, KC_SPC, TT(3), KC_MINS, KC_QUOT, KC_ENT),
	[3] = LAYOUT(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10,
                KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F11,
                KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_F12,    
                KC_NO, KC_NO, TO(2), KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, TO(0), KC_PSCR, KC_NO, KC_NO)
};

